name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify the version you need

      - name: Install Dependencies and Build
        run: npm ci && npm run build  # Adjust if your build command is different

      - name: Deploy to Firebase Hosting
        uses: wzieba/Firebase-Hosting-Action@v2.0.0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_EIN }}
          projectId: test-ein  # Your Firebase project ID
          sourceDir: build  # Adjust if your build output is in a different folder
